#!/bin/bash

if [ "$1" == '-h' ] || [ -z "$1" ] || ! [[ "$1" =~ ^[0-9]+$ ]]
then
    echo "Usage:"
    echo "    $0 [abundance] [title] [body_html]"
    echo
    exit 0
fi


if [ -z "$2" ]
then
    for i in $(seq 1 $1)
    do
        ./post $i $i
    done
elif [ -z "$3" ]
then
    for i in $(seq 1 $1)
    do
        ./post $2 $i
    done
elif [ -z "$4" ]
then
    for i in $(seq 1 $1)
    do
        ./post $2 $3
    done
fi
